theme: jekyll-theme-minimal
title: Suchi Dey
description: A strategy consulting professional with a commercial mind-set. <br><br><br><br><br>
logo: "data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
    9TXL0Y4OHwAAAABJRU5ErkJgg"
