theme: jekyll-theme-minimal
title: Suchi Dey
description: A strategy consulting professional with a commercial mind-set.<img src="https://www.dropbox.com/s/22q5r1qzz9kinzq/img2.jpeg?dl=1">
logo: https://www.dropbox.com/s/22q5r1qzz9kinzq/img2.jpeg?dl=1
